# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b879bdffaa1f438072782fc6aa9e5153dcbf70df1246d41fed3ef85ad79b0fbdad0f232df59f17c5d0d1a0a775e6b761d25be94b1a987b1e1908220e124fc058

test:
  secret_key_base: 03e70cf7a405a7cb91aa916863ecb894212f6c598581691bf5f04b8db20530cd7bb705eef883b1e0070b73f5402ce0429b2b67ab11b38529c04a60e02919b144

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
